### ISSUE TITLE
Pre-Release Todo List

### ISSUE THREAD

**Issue by Pseurae** [Pseurae/gible#1]
- [x] mmap wrapper for Windows.
- [x] Rework how patch formats are handled to be more modular.
- [x] CLI arguments to ignore crc32 checks.
